### ISSUE TITLE
Errors returned by the listDefinition operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#79] opened 2015-05-23 15:09 UTC
It is said that this operation does not return any error.

What happens if the supplied actionNames are unknown, NULL or empty ?

I suggest to describe the listDefinition behaviour in these cases and to add errors (Unknow, Invalid).

**Comment by SamCooper** [comment] 2015-10-22 15:18
Accepted

**Comment by SamCooper** [comment] 2016-03-30 07:26
Duplicate of #11 

Will be closed by that RID

**Closed as completed by SamCooper** 2016-03-30 07:26 UTC
Labels: duplicate
