### ISSUE TITLE
Changes permitted by the updateDefinition operation of the Alert service

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#16] opened 2014-10-29 15:26 UTC
Could the updateDefinition operation not change the attribute "severity" of the AlertDefinitionDetails ?

**Comment by SamCooper** [comment] 2014-11-07 10:49
Duplicate of #12

**Comment by SamCooper** [comment] 2015-03-12 14:06
Done.

**Closed as completed by SamCooper** 2015-03-12 14:06 UTC
Labels: duplicate, wontfix
