### ISSUE TITLE
Errors returned by service operations

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#11] opened 2014-10-29 07:36 UTC
Generally speaking, when an operation takes inputs, the section describing the possible error codes should not be empty because there can always be an unknown or invalid argument in the list of inputs provided. Therefore, the error section of the following operations should be completed:
- listDefinition of the services Action, Parameter, Alert, Check & Aggregation
- getStatistics of the service Statistics
- getcurrentTransitionlist, triggerCheck, addParametercheck of the Check service

**Comment by SamCooper** [comment] 2014-11-07 10:39
Accepted

**Comment by SamCooper** [comment] 2016-03-30 07:26
#79 is a duplicate of this:

It is said that this operation does not return any error.
What happens if the supplied actionNames are unknown, NULL or empty ?
I suggest to describe the listDefinition behaviour in these cases and to add errors (Unknow, Invalid)

Merging into this RID

**Comment by SamCooper** [comment] 2016-05-04 09:57
Done

**Closed as completed by SamCooper** 2016-05-04 09:57 UTC
Labels: MEDIUM
